config/routes.rb
Rails.application.routes.draw do
  #config/routes.rb
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: %i(create destroy)
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("app_name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("navbar.english"), locale: :en %></li>
        <li><%= link_to t("navbar.vietnamese"), locale: :vi %></li>
        <li><%= link_to t("navbar.home"), root_path %></li>
        <li><%= link_to t("navbar.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("navbar.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", id: "account", class: "dropdown-toggle", role: "button", data: { toggle: "dropdown" } do %>
              <%= t "navbar.account" %>
              <b class="caret"></b>
            <% end %>
            <ul id="dropdown-menu" class="dropdown-menu" aria-labelledby="account">
              <li><%= link_to t("navbar.profile"), current_user %></li>
              <li><%= link_to t("navbar.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to t("navbar.logout"), logout_path, data: { "turbo-method": :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("navbar.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>